# Generated by Django 3.2.6 on 2021-09-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_auto_20210831_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover/'),
        ),
    ]
